# Site settings
title: Placid Palms
tag_text: Placid Palms Skool
description: Placid Palms is a space where creativity flows, wisdom reawakens, and inner genius stirs. Its a journey of rediscovery, where every moment reminds you of the boundless energy you possess. 
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
